---
antora:
  name: modules
  dir: www
  modules:
    - name: 01-install
      label: "Install"
      solveButton: true
    - name: 02-verify
      label: "Verify"
      solveButton: true
    - name: 03-update
      label: "Update"
      solveButton: true
    - name: 04-explore
      label: "Explore"
      solveButton: true
    - name: 05-integritycontrols
      label: "Integritycontrols"
      solveButton: true

tabs:
  - name: ">_ terminal"
    url: /wetty
